# Generated by Django 2.1.5 on 2019-02-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor_model',
            old_name='proffesion_mentor',
            new_name='profession_mentor',
        ),
    ]
