# Generated by Django 2.1.5 on 2019-02-13 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_blog', models.TextField(max_length=50)),
                ('cerita_blog', models.TextField()),
                ('foto_blog', models.ImageField(upload_to='blogmedia')),
                ('tanggal_blog', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_blog', models.TextField()),
            ],
        ),
    ]
